spring:
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false
      fail_on_empty_beans: false

prediction-service:
  #url: http://localhost:8081 # local dev
  url: http://inventory-prediction-service-lb-1162006621.us-west-2.elb.amazonaws.com # production